set(NA_VM_SOURCE_FILES
    src/engine_statevector.cpp
    src/cpu_state_backend.cpp
    src/oneapi_state_backend.cpp
    src/noise.cpp
    src/noise/pauli_utils.cpp
    src/noise/amplitude_damping_source.cpp
    src/noise/measurement_noise_source.cpp
    src/noise/single_qubit_pauli_source.cpp
    src/noise/two_qubit_pauli_source.cpp
    src/noise/correlated_pauli_source.cpp
    src/noise/device_pauli_noise_source.cpp
    src/noise/device_noise_builder.cpp
    src/noise/idle_dephasing_source.cpp
    src/noise/phase_kick_noise_source.cpp
    src/noise/idle_phase_drift_source.cpp
    src/noise/loss_tracking_source.cpp
    src/hardware_vm.cpp
    src/stabilizer_backend.cpp
    src/service/job.cpp
    src/service/job_validation.cpp
    src/service/scheduler.cpp
    src/service/job_service.cpp
)
